In [1]:
import tensorflow as tf
import numpy as np
import math

sess = tf.InteractiveSession()

# Some simple constants

x1 = tf.Variable(tf.truncated_normal([5], mean=3, stddev=1./math.sqrt(5)))
x2 = tf.Variable(tf.truncated_normal([5], mean=-1, stddev=1./math.sqrt(5)))
x3 = tf.Variable(tf.truncated_normal([5], mean=0, stddev=1./math.sqrt(5)))


In [2]:
sess.run(tf.initialize_all_variables())

In [3]:
# Squaring makes large values extreme (but positive)
# Be careful if you have negative values

sqx2 = x2 * x2
print(x2.eval())
print(sqx2.eval())


[-1.24405909 -1.62133908 -0.77942348 -0.87037039 -0.75508702]
[ 1.547683    2.62874031  0.60750097  0.75754464  0.5701564 ]


In [5]:

# Logarithm makes small values more pronounced (and negative)
# Be careful that your algorithm can handle negative numbers

logx1 = tf.log(x1)
print(x1.eval())
print(logx1.eval())



[ 3.31315041  2.50278139  3.50320244  2.34984136  2.9814868 ]
[ 1.19789958  0.91740268  1.25367749  0.85434783  1.09242213]


In [6]:
# "sigmoid" is a common transformation in deep learning
# Extreme values get flattened to +1 or 0
sigx3 = tf.sigmoid(x3)
print(x3.eval())
print(sigx3.eval())

[-0.2372137   0.27611151  0.40040392  0.14891461 -0.08319866]
[ 0.44097307  0.56859267  0.59878474  0.53715998  0.47921234]


In [7]:
w1 = tf.constant(0.1)
w2=tf.constant(0.2)
sess.run(tf.initialize_all_variables())

n1 = tf.sigmoid(w1*x1 + w2*x2)
print((w1*x1).eval())
print((w2*x2).eval())
print(n1.eval())

[ 0.3022891   0.2500813   0.2847403   0.37150174  0.32027802]
[-0.2901791  -0.1946023  -0.14195304 -0.14737432 -0.33529058]
[ 0.5030275   0.51386619  0.53563631  0.55579847  0.49624693]
