In [2]:
import theano
from theano import tensor as T, function

import numpy as np


In [6]:
X = T.matrix('x')
Y= X ** 2

Z = T.grad(Y.sum(),X)

F= function([X],[Y,Z])

In [7]:
x = np.ones((2,2))*3
y ,z= F(x)

In [8]:
print(x)
print('-'*12)
print(y)
print('-'*12)
print(z)

[[ 3.  3.]
 [ 3.  3.]]
------------
[[ 9.  9.]
 [ 9.  9.]]
------------
[[ 6.  6.]
 [ 6.  6.]]
